### ISSUE TITLE
Failed to export PWM

### ISSUE THREAD

**Issue by derekwheee** [rwaldron/nino-io#2]
On an Arduino Yun with BusyBox v1.19.4 (2014-10-17 22:40:10 CEST), when running the Node script below, I get the output that follows.

Node script:

``` javascript
var Nino = require("nino-io");
var board = new Nino({
  layout: "Arduino Yun"
});


board.on("ready", function() {
  console.log("Ready.");

  var state = 0;
  var pin = 13;

  this.pinMode(pin, this.MODES.OUTPUT);

  setInterval(function() {
    board.digitalWrite(pin, (state ^= 1));
  }, 500);
});
```

Output:

``` bash
root@yun:/opt/j5# node blink
Failed to export PWM: (ENOENT ENOENT, open '/sys/class/pwm/pwmchip0/export') { ENA: true,
  DEF: 'D3',
  TYP: 'digital',
  NUM: '116',
  MAP: 'D3',
  servo: null,
  pwm: 
   { ENA: true,
     DEF: 'P3',
     TYP: 'pwm',
     MAP: 'D3',
     BIT: '8',
     NUM: '0',
     TIM: { DEF: 'T0', SET: false, USE: [], SHARED: false },
     MAX: 4000000,
     RES: 15625 } }
Failed to export PWM: (ENOENT ENOENT, open '/sys/class/pwm/pwmchip0/export') { ENA: true,
  DEF: 'D5',
  TYP: 'digital',
  NUM: '114',
  MAP: 'D5',
  servo: 
   { ENA: true,
     DEF: 'P5',
     TYP: 'pwm',
     MAP: 'D5',
     BIT: '16',
     NUM: '4',
     TIM: { DEF: 'T1', SET: false, USE: [], SHARED: false },
     MAX: 32768000,
     RES: 500 },
  pwm: 
   { ENA: true,
     DEF: 'P5',
     TYP: 'pwm',
     MAP: 'D5',
     BIT: '16',
     NUM: '4',
     TIM: { DEF: 'T1', SET: false, USE: [], SHARED: false },
     MAX: 32768000,
     RES: 500 } }
Failed to export PWM: (ENOENT ENOENT, open '/sys/class/pwm/pwmchip0/export') { ENA: true,
  DEF: 'D6',
  TYP: 'digital',
  NUM: '123',
  MAP: 'D6',
  servo: null,
  pwm: 
   { ENA: true,
     DEF: 'P6',
     TYP: 'pwm',
     MAP: 'D6',
     BIT: '16',
     NUM: '5',
     TIM: { DEF: 'T2', SET: false, USE: [], SHARED: false },
     MAX: 16384000,
     RES: 64000 } }
Failed to export PWM: (ENOENT ENOENT, open '/sys/class/pwm/pwmchip0/export') { ENA: true,
  DEF: 'D9',
  TYP: 'digital',
  NUM: '105',
  MAP: 'D9',
  servo: 
   { ENA: true,
     DEF: 'P9',
     TYP: 'pwm',
     MAP: 'D9',
     BIT: '16',
     NUM: '1',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 },
  pwm: 
   { ENA: true,
     DEF: 'P9',
     TYP: 'pwm',
     MAP: 'D9',
     BIT: '16',
     NUM: '1',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 } }
Failed to export PWM: (ENOENT ENOENT, open '/sys/class/pwm/pwmchip0/export') { ENA: true,
  DEF: 'D10',
  TYP: 'digital',
  NUM: '106',
  MAP: 'D10',
  servo: 
   { ENA: true,
     DEF: 'P10',
     TYP: 'pwm',
     MAP: 'D10',
     BIT: '16',
     NUM: '2',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 },
  pwm: 
   { ENA: true,
     DEF: 'P10',
     TYP: 'pwm',
     MAP: 'D10',
     BIT: '16',
     NUM: '2',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 } }
Failed to export PWM: (ENOENT ENOENT, open '/sys/class/pwm/pwmchip0/export') { ENA: true,
  DEF: 'D11',
  TYP: 'digital',
  NUM: '107',
  MAP: 'D11',
  servo: 
   { ENA: true,
     DEF: 'P11',
     TYP: 'pwm',
     MAP: 'D11',
     BIT: '16',
     NUM: '3',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 },
  pwm: 
   { ENA: true,
     DEF: 'P11',
     TYP: 'pwm',
     MAP: 'D11',
     BIT: '16',
     NUM: '3',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 } }
Failed to export ADC: (ENOENT ENOENT, open '/sys/bus/iio/devices/iio:device0/enable') 
Ready.

fs.js:524
  binding.write(fd, buffer, offset, length, position, wrapper);
          ^
TypeError: Bad argument
    at Object.fs.write (fs.js:524:11)
    at Pin.write (/opt/j5/node_modules/nino-io/lib/nino-io.js:853:6)
    at Nino.digitalWrite (/opt/j5/node_modules/nino-io/lib/nino-io.js:452:23)
    at null.<anonymous> (/opt/j5/blink.js:16:11)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

The paths on [line 42](https://github.com/rwaldron/nino-io/blob/master/lib/nino-io.js#L42) and [line 43](https://github.com/rwaldron/nino-io/blob/master/lib/nino-io.js#L43) don't exist on my Yun. Are we running different versions of OpenWrt?

**Comment by framlin** [comment]
Servus,
I have the same problem. Runing the code above ends with

  pwm: 
   { ENA: true,
     DEF: 'P11',
     TYP: 'pwm',
     MAP: 'D11',
     BIT: '16',
     NUM: '3',
     TIM: { DEF: 'T3', SET: false, USE: [], SHARED: true },
     MAX: 32768000,
     RES: 500 } }
Failed to export ADC: (ENOENT ENOENT, open '/sys/bus/iio/devices/iio:device0/enable') 
Ready.

fs.js:513
  binding.write(fd, buffer, offset, length, position, wrapper);
          ^
TypeError: Bad argument
    at Object.fs.write (fs.js:513:11)
    at Pin.write (/opt/node_modules/nino-io/lib/nino-io.js:986:6)
    at Nino.digitalWrite (/opt/node_modules/nino-io/lib/nino-io.js:467:23)
    at null.<anonymous> (/opt/src/j5tst/run.js:16:23)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)



is there any solution for this faiulure?

**Comment by frxnz** [comment]
@framlin Currently the only solution for this is to install LininoOS on the Yun. Neither me nor @rwaldron have been successful getting LininoOS installed, and Rick has bricked a few Yuns trying. @aabm00 has had some success in #4 but it's not an easy process by any means.

**Comment by framlin** [comment]
and since I have done all I have read here I am noable to connect to the yun any mor nor via wlan neither via usb/arduino-ide :(
does anyone know how to do a factory-reset without usb or wlan-connection?

**Comment by fivdi** [comment]
@framlin sorry to hear about that. While installing LininoOS and LininoIO on a Linino One I ended up in a situation where it was no longer possible to talk to the Linino One via ethernet / wlan. What did work was using the Linux screen utility as follows `screen /dev/ttyACM0 115200`. It was also necessary to hit `~1` and `~2` to toggle between 250000 and 115200 baud. I somehow managed to get things sorted out over the serial port.

@rwaldron @frxnz The [readme](https://github.com/rwaldron/nino-io) mentions that LininoOS is required, but makes no mention of LininoIO. AFAIK, both are actually needed. After installing LininiOS on a Linino One, it looked to me as if everything required was there, so I went and directly did the Node.js installation. However, important pieces ended up being missing, for example `/dev/i2c-0`. Only after reinstalling LininoOS, upgrading to LininiIO, and then installing Node.js did things function correctly.

**Comment by rwaldron** [comment]
> The readme mentions that LininoOS is required, but makes no mention of LininoIO. AFAIK, both are actually needed.

Ugh, you're absolutely right. Sorry about that :(

Can you make a PR?

**Comment by fivdi** [comment]
Will do.
